class JoBikaApp {
    constructor() {
        this.currentStep = 1;
        this.totalSteps = 4;
        this.idea = '';
        
        this.initializeElements();
        this.attachEventListeners();
    }

    initializeElements() {
        // Steps
        this.steps = document.querySelectorAll('.view');
        this.indicators = document.querySelectorAll('.step');
        this.lines = document.querySelectorAll('.line');
        
        // Inputs & Buttons
        this.ideaInput = document.getElementById('raw-idea-input');
        this.btnRefine = document.getElementById('btn-refine');
        this.btnToClaude = document.getElementById('btn-to-claude');
        this.btnToCode = document.getElementById('btn-to-code');
        this.btnRestart = document.getElementById('btn-restart');
        
        // Output Containers
        this.gptOutput = document.getElementById('gpt-output');
        this.claudeOutput = document.getElementById('claude-output');
        this.finalCode = document.getElementById('final-code');
    }

    attachEventListeners() {
        this.btnRefine.addEventListener('click', () => this.handleRefine());
        this.btnToClaude.addEventListener('click', () => this.handleToClaude());
        this.btnToCode.addEventListener('click', () => this.handleToCode());
        this.btnRestart.addEventListener('click', () => this.resetApp());
    }

    async handleRefine() {
        const input = this.ideaInput.value.trim();
        if (!input) {
            this.ideaInput.style.borderColor = '#ef4444';
            setTimeout(() => this.ideaInput.style.borderColor = '', 2000);
            return;
        }
        
        this.idea = input;
        this.goToStep(2);
        
        // Simulate GPT Streaming
        const gptResponse = `Analyzing concept: "${this.idea.substring(0, 30)}..."\n\n> IDENTIFIED CORE FEATURES:\n- User Authentication (Social Login)\n- Real-time Feed System\n- Image Upload & Optimization\n- Geolocation Services\n\n> REFINING ARCHITECTURE:\nSUGGESTED STACK: React Native + Firebase\n\n> OPTIMIZING USER FLOW:\n1. Onboarding -> Interest Selection\n2. Main Feed -> Swipe Interface\n3. Detail View -> Booking System\n\nAnalysis Complete. Ready for Instruction Generation.`;
        
        await this.typeWriter(this.gptOutput, gptResponse, 30);
        this.btnToClaude.classList.remove('hidden');
        this.btnToClaude.classList.add('visible');
    }

    async handleToClaude() {
        this.goToStep(3);
        
        // Simulate Claude Generation
        const claudeResponse = `PROJECT: JoBika_v1\nCONTEXT: Social App Concept\n\n### SYSTEM INSTRUCTIONS ###\n\n1. COMPONENT STRUCTURE\n   - Create atomic components for FeedCard, UserProfile.\n   - Implement lazy loading for media assets.\n\n2. STATE MANAGEMENT\n   - Use Zustand for global user state.\n   - React Query for server state synchronization.\n\n3. API DEFINITION\n   - POST /api/v1/posts/create\n   - GET /api/v1/feed/nearby\n\n4. SECURITY PROTOCOLS\n   - Implement JWT rotation.\n   - Sanitize all user inputs.\n\nGenerating final CLI implementation plan...`;
        
        await this.typeWriter(this.claudeOutput, claudeResponse, 20);
        this.btnToCode.classList.remove('hidden');
        this.btnToCode.classList.add('visible');
    }

    async handleToCode() {
        this.goToStep(4);
        
        const code = `
# JoBika Final CLI Generator
# Auto-generated by Claude Opus Ultra

import os
import sys

class JoBikaBuilder:
    def __init__(self):
        self.app_name = "JoBika_App"
        self.version = "1.0.0"

    def scaffold(self):
        print(f"🚀 Initializing {self.app_name} v{self.version}...")
        
        # Core Structure
        structure = [
            "src/components/auth",
            "src/components/feed",
            "src/hooks",
            "src/utils"
        ]
        
        for path in structure:
            print(f"  [+] Creating {path}...")
            
        print("\\n✨ Dependencies installed.")
        print("✨ Security protocols active.")
        print("✨ AI Agents ready.")
        
    def deploy(self):
        print("\\n✅ BUILD SUCCESSFUL")
        print(f"Run 'cd {self.app_name} && npm start' to launch.")

if __name__ == "__main__":
    builder = JoBikaBuilder()
    builder.scaffold()
    builder.deploy()
`;
        this.finalCode.textContent = code;
    }

    goToStep(stepNumber) {
        // Update View
        this.steps.forEach(step => step.classList.remove('active'));
        document.getElementById(`step-${stepNumber}`).classList.add('active');
        
        // Update Indicators
        this.indicators.forEach((indicator, index) => {
            if (index + 1 <= stepNumber) {
                indicator.classList.add('active');
                if (index + 1 < stepNumber) indicator.classList.add('completed');
            } else {
                indicator.classList.remove('active', 'completed');
            }
        });

        // Update Lines
        this.lines.forEach((line, index) => {
            if (index + 1 < stepNumber) {
                line.classList.add('active');
            } else {
                line.classList.remove('active');
            }
        });

        this.currentStep = stepNumber;
    }

    resetApp() {
        this.ideaInput.value = '';
        this.gptOutput.textContent = '';
        this.claudeOutput.textContent = '';
        this.btnToClaude.classList.remove('visible');
        this.btnToClaude.classList.add('hidden');
        this.btnToCode.classList.remove('visible');
        this.btnToCode.classList.add('hidden');
        this.goToStep(1);
    }

    typeWriter(element, text, speed) {
        return new Promise(resolve => {
            let i = 0;
            element.textContent = '';
            function type() {
                if (i < text.length) {
                    element.textContent += text.charAt(i);
                    i++;
                    element.scrollTop = element.scrollHeight;
                    setTimeout(type, speed);
                } else {
                    resolve();
                }
            }
            type();
        });
    }
}

// Initialize App
document.addEventListener('DOMContentLoaded', () => {
    new JoBikaApp();
});
